### ISSUE TITLE
Where to put tooling?

### ISSUE THREAD

**Issue by jordansissel** [davedash/parental-leave#31]
I wrote a little tool to upload this into Elasticsearch so we can explore this data in Kibana. Yay visuals!

I've made Kibana available to all who want to play:

https://f29fa6d0ef52390bc7bd13585ee02711.us-east-1.aws.found.io/app/kibana#/dashboard/Parental-Leave

Credentials: family/family

I'll see about leaving this cluster up somewhat-permanently and somehow getting it a more palatable URL :)

Thoughts? Here's a sample:

<img width="800" alt="screen shot 2015-11-16 at 7 52 59 pm" src="https://cloud.githubusercontent.com/assets/131818/11202372/5a4c5526-8c9c-11e5-8d4c-d8c3a3b298fa.png">

Quick script to ship the yaml into ES lives here for now: https://github.com/jordansissel/experiments/tree/master/ruby/parental-leave

**Comment by davedash** [comment]
Amazing.

I'd be happy to have this live in this repo until it becomes gross - maybe in a `scripts` folder.

I can throw in some data-adjusting things too, because now men and women get different amounts of leave for adoption... sigh.

**Comment by jordansissel** [comment]
Ok cool! I'll send a PR. <3
